In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline

In [2]:
df = pd.read_csv('cleaneddata.csv')

In [3]:
df = df.drop(columns=['waterfront','view', 'Unnamed: 0'])

In [4]:
#one hot encoding zipcodes
zipcode = df['zipcode'].values.reshape(-1,1)

In [5]:
encoder = OneHotEncoder(categories='auto').fit(zipcode)

In [6]:
ohe = pd.DataFrame(encoder.transform(zipcode).toarray(),
                  columns=encoder.get_feature_names(['zipcode']))

In [7]:
df_ohe = pd.concat([df.drop(columns='zipcode'), ohe], axis=1)

In [8]:
df_ohe.to_csv(path_or_buf='clean_ohe.csv', index=False)

In [9]:
test = pd.read_csv('clean_ohe.csv')
test.head().T

                           0           1           2           3           4
id                7129300520  6414100192  5631500400  2487200875  1954400510
date              2014-10-13  2014-12-09  2015-02-25  2014-12-09  2015-02-18
price                 221900      538000      180000      604000      510000
bedrooms                   3           3           2           4           3
bathrooms                  1        2.25           1           3           2
sqft_living             1180        2570         770        1960        1680
sqft_lot                5650        7242       10000        5000        8080
floors                     1           2           1           1           1
condition                  3           3           3           5           3
grade                      7           7           6           7           8
sqft_above              1180        2170         770        1050        1680
sqft_basement              0         400           0         910           0
yr_built                1955        1951        1933        1965        1987
yr_renovated            1955        1991        1933        1965        1987
lat                  47.5112      47.721     47.7379     47.5208     47.6168
long                -122.257    -122.319    -122.233    -122.393    -122.045
sqft_living15           1340        1690        2720        1360        1800
sqft_lot15              5650        7639        8062        5000        7503
waterfront_clean           0           0           0           0           0
view_clean                 0           0           0           0           0
zipcode_98001              0           0           0           0           0
zipcode_98002              0           0           0           0           0
zipcode_98003              0           0           0           0           0
zipcode_98004              0           0           0           0           0
zipcode_98005              0           0           0           0           0
zipcode_98006              0           0           0           0           0
zipcode_98007              0           0           0           0           0
zipcode_98008              0           0           0           0           0
zipcode_98010              0           0           0           0           0
zipcode_98011              0           0           0           0           0
...                      ...         ...         ...         ...         ...
zipcode_98092              0           0           0           0           0
zipcode_98102              0           0           0           0           0
zipcode_98103              0           0           0           0           0
zipcode_98105              0           0           0           0           0
zipcode_98106              0           0           0           0           0
zipcode_98107              0           0           0           0           0
zipcode_98108              0           0           0           0           0
zipcode_98109              0           0           0           0           0
zipcode_98112              0           0           0           0           0
zipcode_98115              0           0           0           0           0
zipcode_98116              0           0           0           0           0
zipcode_98117              0           0           0           0           0
zipcode_98118              0           0           0           0           0
zipcode_98119              0           0           0           0           0
zipcode_98122              0           0           0           0           0
zipcode_98125              0           1           0           0           0
zipcode_98126              0           0           0           0           0
zipcode_98133              0           0           0           0           0
zipcode_98136              0           0           0           1           0
zipcode_98144              0           0           0           0           0
zipcode_98146              0           0           0           0           0
zipcode_98148              0           0           0           0           0
zipcode_98155              0           0           0           0           0
zipcode_98166              0           0           0           0           0
zipcode_98168              0           0           0           0           0
zipcode_98177              0           0           0           0           0
zipcode_98178              1           0           0           0           0
zipcode_98188              0           0           0           0           0
zipcode_98198              0           0           0           0           0
zipcode_98199              0           0           0           0           0

[90 rows x 5 columns]